/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -p fcitxinputcontextproxy -c FcitxInputContextProxy interfaces/org.fcitx.Fcitx.InputContext.xml -i fcitxformattedpreedit.h -i fcitxqt_export.h
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "fcitxinputcontextproxy.h"

/*
 * Implementation of interface class FcitxInputContextProxy
 */

FcitxInputContextProxy::FcitxInputContextProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FcitxInputContextProxy::~FcitxInputContextProxy()
{
}

