.TH mb2txt 1 "2010-12-16"
.SH NAME
mb2txt, txt2mb \- fcitx table related tools
.SH SYNOPSIS
.PP
.B mb2txt \fI<mbfile>\fR
.PP
.B txt2mb \fI<txtfile>\fR
.SH DESCRIPTION
.B mb2txt
and
.B txt2mb
are tools for transform table file between binary format and text format. fcitx can only use binary format.
All output of
.B mb2txt
and
.B txt2mb
will be stdout.
.SH SEE ALSO
Please see the homepage at
.BR http://www.fcitx.org/
and
.BR http://fcitx.googlecode.com/
