Document: fcitx
Title: Debian fcitx Manual
Author: <insert document author here>
Abstract: This manual describes what fcitx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fcitx/fcitx.sgml.gz

Format: postscript
Files: /usr/share/doc/fcitx/fcitx.ps.gz

Format: text
Files: /usr/share/doc/fcitx/fcitx.text.gz

Format: HTML
Index: /usr/share/doc/fcitx/html/index.html
Files: /usr/share/doc/fcitx/html/*.html

  
