CC = gcc

CFLAGS= -O2 -fno-strength-reduce -Wall -D_USE_XFT -DPKGDATADIR=\"/usr/share/fcitx/\"

INC = `xft-config --cflags` -I../lib -I../xpm

SRC =  main.c

LIB = `xft-config --libs`

OBJ = $(SRC:.c=.o)

all: libXimd.a fcitx

fcitx: $(OBJ) ../lib/libXimd.a
	$(CC) $(CFLAGS) $(LIB) $(OBJ) ../lib/libXimd.a -o fcitx
	
libXimd.a:
	cd ../lib; make

.c.o:
	$(CC) -c $(CFLAGS) $(INC) $<

clean:
	rm -f *.o fcitx fcitx.noxft
	cd ../lib; make clean

install:
	mkdir -p /usr/share/fcitx
	install -s fcitx /usr/bin/
	cp -f data/punc.mb /usr/share/fcitx/
	cp -f data/wbx.mb /usr/share/fcitx/
	cp -f data/pybase.mb /usr/share/fcitx/
	cp -f data/pyphrase.mb /usr/share/fcitx/
install_local:
	mkdir -p ${HOME}/fcitx/
	install -s fcitx ${HOME}/fcitx/
	cp -f data/punc.mb ${HOME}/fcitx/
	cp -f data/wbx.mb ${HOME}/fcitx/
	cp -f data/pybase.mb ${HOME}/fcitx/
	cp -f data/pyphrase.mb ${HOME}/fcitx/
	mkdir -p ${HOME}/bin/
	echo "#!/bin/sh" > ${HOME}/bin/fcitx
	echo "${HOME}/fcitx/fcitx -local">>${HOME}/bin/fcitx
	chmod 755 ${HOME}/bin/fcitx
uninstall:
	rm -f /usr/bin/fcitx
	rm -fr /usr/share/fcitx
uninstall_local:
	rm -f ${HOME}/bin/fcitx
	rm -fr ${HOME}/fcitx
